courses/urls.py
from django.conf.urls import patterns, url
from django.views.generic import DetailView, ListView
from courses.models import Course

urlpatterns = patterns('',
#   url(r'^$', views.index, name='index'),
#    url(r'^(?P<courses_id>\d+)/$', views.detail, name='detail'),
    url(r'^courselist',
        ListView.as_view(
            queryset=Course.objects.order_by('-name')[:20],
            context_object_name='latest_courses_list',
            template_name='courses/courselist.html'),
        name='courselist'),
    url(r'^(?P<pk>\d+)/$',
        DetailView.as_view(
            model=Course,
            template_name='courses/detail.html'),
        name='detail'),
    url(r'^$',
        ListView.as_view(
            queryset=Course.objects.order_by('-name')[:2],
            context_object_name='latest_courses_list',
            template_name='courses/index.html'),
        name='index'),
    url(r'^faq',
        ListView.as_view(
			model=Course,
            template_name='courses/faq.html'),
        name='faq'),
    url(r'^contact',
        ListView.as_view(
			model=Course,
            template_name='courses/contact.html'),
        name='contact'),
)

jmr/urls.py
from django.conf.urls import patterns, include, url

from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.contrib import admin
from django.views.generic import DetailView, ListView
from courses.models import Course
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    #url(r'^$', 'jmr.views.home', name='home'),
    # url(r'^jmr/', include('jmr.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^schedules/', include('schedules.urls', namespace="schedules")),
)

registration/backends/default/urls.py
"""
URLconf for registration and activation, using django-registration's
default backend.

If the default behavior of these views is acceptable to you, simply
use a line like this in your root URLconf to set up the default URLs
for registration::

    (r'^accounts/', include('registration.backends.default.urls')),

This will also automatically set up the views in
``django.contrib.auth`` at sensible default locations.

If you'd like to customize the behavior (e.g., by passing extra
arguments to the various views) or split up the URLs, feel free to set
up your own URL patterns for these views instead.

"""


from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from registration.views import activate
from registration.views import register


urlpatterns = patterns('',
                       url(r'^activate/complete/$',
                           direct_to_template,
                           { 'template': 'registration/activation_complete.html' },
                           name='registration_activation_complete'),
                       # Activation keys get matched by \w+ instead of the more specific
                       # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
                       # that way it can return a sensible "invalid key" message instead of a
                       # confusing 404.
                       url(r'^activate/(?P<activation_key>\w+)/$',
                           activate,
                           { 'backend': 'registration.backends.default.DefaultBackend' },
                           name='registration_activate'),
                       url(r'^register/$',
                           register,
                           { 'backend': 'registration.backends.default.DefaultBackend' },
                           name='registration_register'),
                       url(r'^register/complete/$',
                           direct_to_template,
                           { 'template': 'registration/registration_complete.html' },
                           name='registration_complete'),
                       url(r'^register/closed/$',
                           direct_to_template,
                           { 'template': 'registration/registration_closed.html' },
                           name='registration_disallowed'),
                       (r'', include('registration.auth_urls')),
                       )

registration/urls.py
"""
Backwards-compatible URLconf for existing django-registration
installs; this allows the standard ``include('registration.urls')`` to
continue working, but that usage is deprecated and will be removed for
django-registration 1.0. For new installs, use
``include('registration.backends.default.urls')``.

"""

import warnings

warnings.warn("include('registration.urls') is deprecated; use include('registration.backends.default.urls') instead.",
              PendingDeprecationWarning)

from registration.backends.default.urls import *

schedules/urls.py
from django.conf.urls import patterns, url
from django.views.generic import DetailView, ListView
from schedules.models import CourseSchedule

urlpatterns = patterns('',
#   url(r'^$', views.index, name='index'),
#    url(r'^(?P<courses_id>\d+)/$', views.detail, name='detail'),
    url(r'^$',
        ListView.as_view(
            queryset=CourseSchedule.objects.order_by('-start_date')[:5],
            context_object_name='latest_scheduled_courses_list',
            template_name='schedules/index.html'),
        name='index'),
    url(r'^(?P<pk>\d+)/$',
        DetailView.as_view(
            model=CourseSchedule,
            template_name='schedules/detail.html'),
        name='detail'),
)

store/localsite/urls.py
from django.conf.urls.defaults import *


urlpatterns = patterns('',
    (r'example/', 'simple.localsite.views.example', {}),
)

store/urls.py
from django.conf.urls.defaults import *

from satchmo_store.urls import urlpatterns

courses/models.py
from django.db import models
# New models.
class Course(models.Model):
    name = models.CharField(max_length=60)
    course_description = models.TextField(blank=True)
    num_places = models.PositiveIntegerField()
    price = models.DecimalField(decimal_places=2,max_digits=7)
    course_category = models.CharField(max_length=60)
    def __unicode__(self):
        return self.name

class Lecturer(models.Model):
    first_name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    title = models.CharField(max_length=10)
    email = models.EmailField(blank=True)
    def __unicode__(self):
        return self.first_name + " " + self.surname
    
    

class Event(models.Model):
    course = models.ForeignKey(Course)
    duration = models.PositiveIntegerField()
    name = models.CharField(max_length=60)
    lecturer = models.ForeignKey(Lecturer)
    def __unicode__(self):
        return self.name

schedules/models.py
from django.db import models
from courses.models import Course, Event

class CourseSchedule(models.Model):
    start_date = models.DateField()
    start_time = models.TimeField()
    course = models.ForeignKey(Course)
    def __unicode__(self):
        return unicode(self.course)

class EventSchedule(models.Model):
    start_date = models.DateField()
    start_time = models.TimeField()
    course_schedule = models.ForeignKey(CourseSchedule)
    event = models.ForeignKey(Event)
    def __unicode__(self):
        return unicode(self.event)

jmr/views.py
from django.http import HttpResponse
from courses.models import Course, Event, Lecturer
from schedules.models import CourseSchedule, EventSchedule

def home(request):
    content = "<h1>UCC Summer Courses!</h1>"
    content += "<a href=\"/\">Home</a>"
    content += " - "
    content += "<a href=\"schedules/\">Timetabled Courses</a>"
    content += " - "
    content += "<a href=\"courses/\">Courses we've run in the past</a>"
    content += " - "
    content += "<a href=\"account/login/\">Log in</a>"
    html = "<html><body>" + content + "</body></html>"
    return HttpResponse(html)

schedules/views.py
# Create your views here.

store/localsite/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext

def example(request):
    ctx = RequestContext(request, {})
    return render_to_response('localsite/example.html', context_instance=ctx)

templates/base.html
{% load url from future %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>UCC Summer Courses</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
	{% load staticfiles %}
    <link href="{{ STATIC_URL }}assets/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <link href="{{ STATIC_URL }}assets/css/bootstrap.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">UCC Summer Courses</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li><a href="{% url 'courses:index' %}">Home</a></li>
              <li><a href="{% url 'courses:courselist' %}">Course Info</a></li>
			  <li><a href="{% url 'courses:faq' %}">FAQ</a></li>
              <li><a href="{% url 'courses:contact' %}">Contact</a></li>
            </ul>
			<div class="links pull-right">
				<a href="/accounts/register">Register</a>
				<a href="/accounts/login">Log in</a>
				<a href="/admin">Admin</a>
			</div>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    {% block content %}Empty page{% endblock %}

      <hr>

      <footer>
        <p>&copy; JMR Inc. 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{ STATIC_URL }}assets/js/jquery.js"></script>
    <script src="{{ STATIC_URL }}assets/js/bootstrap-transition.js"></script>
    <script src="{{ STATIC_URL }}assets/js/bootstrap-alert.js"></script>
    <script src="{{ STATIC_URL }}assets/js/bootstrap-modal.js"></script>
    <script src="{{ STATIC_URL }}assets/js/bootstrap-dropdown.js"></script>
    <script src="{{ STATIC_URL }}assets/js/bootstrap-scrollspy.js"></script>
    <script src=".{{ STATIC_URL }}assets/js/bootstrap-tab.js"></script>
    <script src="{{ STATIC_URL }}assets/js/bootstrap-tooltip.js"></script>
    <script src="{{ STATIC_URL }}assets/js/bootstrap-popover.js"></script>
    <script src="{{ STATIC_URL }}assets/js/bootstrap-button.js"></script>
    <script src="{{ STATIC_URL }}assets/js/bootstrap-collapse.js"></script>
    <script src="{{ STATIC_URL }}assets/js/bootstrap-carousel.js"></script>
    <script src="{{ STATIC_URL }}assets/js/bootstrap-typeahead.js"></script>

  </body>
</html>

templates/courses/contact.html
{% extends "base.html" %}

{% load url from future %}

{% block content %}

    <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <!--<h1 style="background-color:rgba(0, 0, 0, 0.7)">UCC Summer Courses</h1>-->
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span6">
          <h2>Contact Details</h2>
		  
		  <table class="table">
			<tr>
				<th valign="top" rowspan="4">Address:</td>
				<td>UCC Summer Courses</td>
			</tr>
			<tr>
				<td>Address Line 1</td>
			</tr>
			<tr>
				<td>Address Line 2</td>
			</tr>
			<tr>
				<td>Address Line 3</td>
			</tr>
			<tr>
				<th>E-Mail:</td>
				<td>UCCSC@example.com</td>
			</tr>
			<tr>
				<th>Phone:</td>
				<td>021-xxx-xxxx</td>
			</tr>
		  </table>
		  
        </div>
	  
	    <div class="span6">
		  
		  <form class="message" action="" method="get">
		    <h2>Send us a message!</h2>
            <div>
              <label for="name">Name:</label>
              <input type="text" name="name" id="fname" size="12" maxlength="30" />
            </div>
			<div>
              <label for="email">E-mail:</label>
              <input type="text" name="email" id="email" size="12" maxlength="30" />
            </div>
			<div>
              <label for="title">Message title:</label>
              <input type="text" name="title" id="title" size="12" maxlength="50" />
            </div>
			<div>
              <label for="title">Message:</label>
              <textarea name="message"cols="20" rows="7"></textarea>
            </div>
            <div id="button_contact">
              <input class="btn btn-small btn-primary" type="submit" value="Send!" />
              <input class="btn btn-small btn-primary" type="reset" />
            </div>
          </form>

		 
		  
      </div>
	  
	  </div>
	  
{% endblock %}

templates/courses/courselist.html
{% extends "base.html" %}

{% load url from future %}

{% block content %}

    <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">

      </div>
	  
	  <div class="row">

      <!-- Example row of columns -->
		
{% if latest_courses_list %}
    {% for course in latest_courses_list %}
	<div>
	<div class="span8">
		<h3>{{ course.name }}</h3>
		<p>{{ course.course_description }}</p>
		<p><a class="btn" href="{% url 'courses:detail' course.id %}">View details &raquo;</a></p>
	</div>
	
	<div class="span4">
		<img src="{{ STATIC_URL }}assets/img/image.png" alt="Picture" />
	</div>
	</div>
    {% endfor %}
{% else %}
    <p>No courses are available.</p>
{% endif %}
       </div>

{% endblock %}

templates/courses/detail.html
{% extends "base.html" %}

{% load url from future %}

{% block content %}

    <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
      </div>

	<div class="row">
      <!-- Example row of columns -->
		
        <div class="span11">
<h1>{{ course.name }}</h1>

<img src="{{ STATIC_URL }}assets/img/image.png" alt="Picture" />

<p><span>00/00/0000 - 00/00/0000</span></p>
<p><span>Description:</span> {{ course.course_description }}</p>
<p><span>Number of places:</span> {{ course.num_places }}</p>
<p><span>Price:</span> {{course.price }}</p>
<br/>
<h3>Course Schedule</h3>

<table class="table">
<tr><title>Events</title></tr>
<tr>
	<th>Day</th>
	<th>Event</th>
	<th>Time</th>
	<th>Duration (min)</th>
	<th>Lecturer</th>
</tr>
{% for event in course.event_set.all %}
    <tr>
    <td>{{ event.event_day_num }}</td>
    <td>{{ event.name }}</td>
	<td>{{event.time_of_day}}</td>
	<td>{{event.duration}}</td>
	<td>Tom Brady</td>
	</tr>
{% endfor %}
</table>
       </div>
      </div>

{% endblock %}

templates/courses/example.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Bootstrap, from Twitter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Project name</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <h1>Bootstrap starter template</h1>
      <p>Use this document as a way to quick start any new project.<br> All you get is this message and a barebones HTML document.</p>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../assets/js/jquery.js"></script>
    <script src="../assets/js/bootstrap-transition.js"></script>
    <script src="../assets/js/bootstrap-alert.js"></script>
    <script src="../assets/js/bootstrap-modal.js"></script>
    <script src="../assets/js/bootstrap-dropdown.js"></script>
    <script src="../assets/js/bootstrap-scrollspy.js"></script>
    <script src="../assets/js/bootstrap-tab.js"></script>
    <script src="../assets/js/bootstrap-tooltip.js"></script>
    <script src="../assets/js/bootstrap-popover.js"></script>
    <script src="../assets/js/bootstrap-button.js"></script>
    <script src="../assets/js/bootstrap-collapse.js"></script>
    <script src="../assets/js/bootstrap-carousel.js"></script>
    <script src="../assets/js/bootstrap-typeahead.js"></script>

  </body>
</html>

templates/courses/faq.html
{% extends "base.html" %}

{% load url from future %}

{% block content %}

    <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <!--<h1 style="background-color:rgba(0, 0, 0, 0.7)">UCC Summer Courses</h1>-->
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span12">
          <h2>Frequently Asked Questions</h2>
          <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi tempor gravida lorem id rutrum. Vivamus porttitor purus nec velit consequat suscipit. Nullam aliquam molestie tellus, a molestie dolor fermentum id. In velit erat, mattis sed pretium vel, fringilla condimentum nisl. Donec nec euismod augue. Nulla viverra felis in velit faucibus eu varius nisl porta. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
		  </p>

<p>Morbi auctor consequat eros, eu ultricies quam interdum ut. Vivamus ac erat erat. Maecenas quis libero id dui vehicula faucibus. Integer pharetra justo nec elit malesuada blandit quis sit amet urna. Cras fringilla scelerisque pulvinar. Nunc at diam a leo congue dapibus. Nam ullamcorper ornare ligula nec luctus. Vestibulum eget leo id ipsum pellentesque pellentesque vitae vel magna. Curabitur ut massa nec dui sagittis blandit. Cras rutrum sem a est condimentum sed fringilla lorem lacinia. Aliquam interdum, mauris id venenatis egestas, dolor leo vestibulum odio, nec fringilla turpis massa vitae augue. Donec id odio purus, vel pulvinar est. Quisque eleifend pharetra malesuada. Maecenas non magna diam, imperdiet posuere lorem. Cras lorem nisi, adipiscing eu ultrices non, rutrum sed enim. Cras rutrum tristique semper.  </p>

      </div>
	  </div>
	  
{% endblock %}

templates/courses/index.html
{% load url from future %}

{% if latest_courses_list %}
    <ul>
    {% for course in latest_courses_list %}
		<li><a href="{% url 'courses:detail' course.id %}">{{ course.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No courses are available.</p>
{% endif %}

templates/main/index.html
{% extends "base.html" %}

{% load url from future %}

{% block content %}

    <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <!--<h1 style="background-color:rgba(0, 0, 0, 0.7)">UCC Summer Courses</h1>-->
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span8">
          <h2>Welcome to UCC Summer Courses!</h2>
          <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi tempor gravida lorem id rutrum. Vivamus porttitor purus nec velit consequat suscipit. Nullam aliquam molestie tellus, a molestie dolor fermentum id. In velit erat, mattis sed pretium vel, fringilla condimentum nisl. Donec nec euismod augue. Nulla viverra felis in velit faucibus eu varius nisl porta. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
		  </p>

<p>Morbi auctor consequat eros, eu ultricies quam interdum ut. Vivamus ac erat erat. Maecenas quis libero id dui vehicula faucibus. Integer pharetra justo nec elit malesuada blandit quis sit amet urna. Cras fringilla scelerisque pulvinar. Nunc at diam a leo congue dapibus. Nam ullamcorper ornare ligula nec luctus. Vestibulum eget leo id ipsum pellentesque pellentesque vitae vel magna. Curabitur ut massa nec dui sagittis blandit. Cras rutrum sem a est condimentum sed fringilla lorem lacinia. Aliquam interdum, mauris id venenatis egestas, dolor leo vestibulum odio, nec fringilla turpis massa vitae augue. Donec id odio purus, vel pulvinar est. Quisque eleifend pharetra malesuada. Maecenas non magna diam, imperdiet posuere lorem. Cras lorem nisi, adipiscing eu ultrices non, rutrum sed enim. Cras rutrum tristique semper.  </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
		
        <div class="span4">
          <h3>Latest Courses</h3>
		  
{% if latest_courses_list %}
    {% for course in latest_courses_list %}
		<h4>{{ course.name }}</h4>
		<p>{{ course.course_description }}</p>
		<p><a class="btn" href="{% url 'courses:detail' course.id %}">View details &raquo;</a></p>
		<br/>
    {% endfor %}
{% else %}
    <p>No courses are available.</p>
{% endif %}

       </div>

      </div>
	  
{% endblock %}

templates/schedules/detail.html
<h1>{{ courseschedule.course.name }}</h1>

<table>
<tr><title>Events</title></tr>
<tr>
	<th>Date</th>
	<th>Event</th>
	<th>Time</th>
	<th>Duration</th>
	<th>Lecturer</th>
</tr>

{% for eventschedule in courseschedule.eventschedule_set.all %}
    <tr>
    <td>{{ eventschedule.start_date }}</td>
    <td>{{ eventschedule.event.name }}</td>
	<td>{{eventschedule.start_time}}</td>
	<td>{{eventschedule.event.duration}} minutes</td>
	<td>{{eventschedule.event.lecturer.title}} {{eventschedule.event.lecturer.first_name}} {{eventschedule.event.lecturer.surname}}</td>
	</tr>
{% endfor %}
</table>

templates/schedules/index.html
{% load url from future %}

{% if latest_scheduled_courses_list %}
    <ul>
    {% for course_schedule in latest_scheduled_courses_list %}
		<li><a href="{% url 'schedules:detail' course_schedule.id %}">{{ course_schedule.course.name }}</a>
		-
		Starts on: <b>{{ course_schedule.start_date}}</b> at <b>{{course_schedule.start_time}}</b></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No courses are planned.</p>
{% endif %}